---
router_id: 10.255.0.2
loopback_ip: 10.255.0.2
mgmt_vlan_id: 99
mgmt_ip: 10.10.99.3
transit_vlan_id: 100
transit_ip: 10.10.100.3
fw_transit_ip: 10.10.100.1

vlans: "{{ vlans_hq }}"
hsrp_active_vlans: [20]
hsrp_standby_vlans: [10, 30, 99]
